### ISSUE TITLE
fixed chessboard squares?

### ISSUE THREAD

**Issue by oakmac** [jennypenfield/css-layouts#1]
Can you figure out a way to make sure the chessboard square are always "square", regardless of the width of the parent container?

![jenny-squeezed-chessboard](https://cloud.githubusercontent.com/assets/98485/23596859/08e17d0a-01f4-11e7-9a30-f5c26ef895c7.png)

**Comment by jennypenfield** [comment]
I've updated the chessboard html and css files with the correct flexbox properties.

**Comment by oakmac** [comment]
Fixed with commit [#7037181cc](https://github.com/jennypenfield/css-layouts/commit/7037181ccafee330e621aa2e32f4376522df9643)

Looks great! Nice job :+1:
